### ISSUE TITLE
[support] - unable to install on ubuntu - username and password requested ..

### ISSUE THREAD

**Issue by wishwanto** [Flax-Network/flax-blockchain#18]
posting here as the other categories results in a 404 error.

installing via CLI and using "git clone https://github.com/Chia-Network/flax-blockchain.git -b latest --recurse-submodules"
results in a username and password being requested for github.. does not happen when installing chia.

Anyone know how to proceed from this point? I trried using my github credentials but got a error.

**Comment by gryan315** [comment]
Have you tried without the -b latest argument?

**Comment by wishwanto** [comment]
thanks for the suggestion, it did not make a difference. dropping all of the arguments also made no difference, it does appear that the installation media on github is password protected.

**Comment by wishwanto** [comment]
Solved the issue, I had not replaced all references to Chia in the command used.
