### ISSUE TITLE
无法同步

### ISSUE THREAD

**Issue by qq2504021719** [Flax-Network/flax-blockchain#21]
2021-07-07T17:01:34.586 harvester flax.harvester.harvester: WARNING  Not farming any plots on this harvester. Check your configuration.
2021-07-07T17:02:29.794 full_node full_node_server        : WARNING  Banning node-12.flaxnetwork.org for 10 seconds
2021-07-07T17:02:29.795 full_node full_node_server        : WARNING  Invalid handshake with peer {'host': 'node-12.flaxnetwork.org', 'port': 6888}. Maybe the peer is running old software.
2021-07-07T17:02:29.797 full_node flax.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
  File "flax\rpc\rpc_server.py", line 212, in safe_handle
  File "flax\rpc\rpc_server.py", line 200, in ws_api
  File "flax\rpc\rpc_server.py", line 161, in open_connection
ValueError: Start client failed, or server is not set

2021-07-07T17:03:21.269 full_node flax.rpc.rpc_server     : WARNING  Error while handling message: Traceback (most recent call last):
  File "flax\rpc\rpc_server.py", line 212, in safe_handle
  File "flax\rpc\rpc_server.py", line 200, in ws_api
  File "flax\rpc\rpc_server.py", line 161, in open_connection
ValueError: Start client failed, or server is not set

**Comment by ToyYan** [comment]
Introduce you to some nodes

`flax show add 222.90.143.214:6888
flax show add 121.27.248.76:6888
flax show add 222.209.84.72:6888
flax show add 203.187.182.140:6888
flax show add 60.1.21.245:6888
flax show add 119.50.172.36:6888
flax show add 122.158.20.207:6888
flax show add 171.117.137.195:6888
flax show add 222.134.85.106:6888
flax show add 171.93.87.153:6888
flax show add 106.122.215.74:6888
flax show add 114.223.165.189:6888
flax show add 115.197.184.152:6888
flax show add 183.251.160.169:6888
flax show add 61.149.217.88:6888
flax show add 182.108.99.227:6888
flax show add 182.108.99.227:6888
flax show add 27.196.247.38:6888
flax show add 111.21.115.14:6888
flax show add 58.32.246.10:6888
flax show add 101.64.226.20:6888
flax show add 171.41.214.152:6888
flax show add 27.188.34.225:6888
flax show add 118.114.228.230:6888
flax show add 59.36.190.110:6888
flax show add 123.173.122.229:6888
flax show add 113.128.133.3:6888
flax show add 171.113.123.228:6888
flax show add 139.214.36.144:6888
flax show add 117.9.54.115:6888
flax show add 61.181.210.189:6888
flax show add 112.22.118.30:6888
flax show add 183.50.36.224:6888
flax show add 218.26.54.126:6888
flax show add 182.151.122.164:6888
flax show add 113.70.241.155:6888
flax show add 117.57.44.220:6888
flax show add 59.63.204.33:6888
flax show add 122.242.98.49:6888
flax show add 218.66.175.149:6888
flax show add 49.77.95.243:6888
flax show add 111.199.189.146:6888
flax show add 223.74.174.177:6888
flax show add 60.223.226.106:6888
flax show add 117.44.91.212:6888
flax show add 116.8.102.211:6888
flax show add 58.214.136.123:6888
flax show add 123.146.180.93:6888
flax show add 123.186.76.240:6888
flax show add 39.90.68.203:6888
flax show add 114.228.200.75:6888
flax show add 120.229.38.125:6888
flax show add 182.127.61.118:6888
flax show add 111.85.32.59:6888
flax show add 119.123.135.72:6888
flax show add 116.252.28.102:6888
flax show add 120.244.28.228:6888
flax show add 124.236.136.186:6888
flax show add 59.55.44.117:6888
flax show add 222.210.188.112:6888
flax show add 117.28.50.112:6888
flax show add 115.227.67.35:6888
flax show add 180.137.103.59:6888
flax show add 221.236.101.91:6888
flax show add 220.202.238.27:6888
flax show add 113.118.79.183:6888
flax show add 117.80.184.28:6888
flax show add 222.79.16.159:6888
flax show add 118.113.23.127:6888
flax show add 182.46.194.176:6888
flax show add 113.78.114.235:6888
flax show add 180.127.62.61:6888
flax show add 123.149.10.93:6888
flax show add 36.5.116.215:6888
flax show add 114.107.92.59:6888
flax show add 125.239.42.255:6888
flax show add 86.3.220.20:6888
flax show add 113.236.19.18:6888
flax show add 171.223.35.39:6888
flax show add 113.141.220.67:6888`

**Comment by anshengme** [comment]
> flax show add 222.90.143.214:6888

```bash
(venv) root@xxxx:~# flax show add 222.90.143.214:6888
Usage: flax show [OPTIONS]
Try 'flax show -h' for help.

Error: Got unexpected extra arguments (add 222.90.143.214:6888)
```

**Comment by flax-dev** [comment]
@anshengme Try `flax show -a ...`
