### ISSUE TITLE
stuck at main screen. 

### ISSUE THREAD

**Issue by beusik** [Flax-Network/flax-blockchain#29]
I open the exe file and that circle just spins and spins. I don not receive any options to make a new key or import from menomics
please help thanks. it is stuck at the connecting to wallet screen. tried uninstalling and reinstalling. it worked till i tried the pooling version. after i tried to install that version it wouldnt work

**Comment by ceyhuntansu** [comment]
same situation
![screenshot](https://user-images.githubusercontent.com/87825806/126681081-b3dd286a-accf-435f-8a01-6478a0c7cce5.jpg)
![screenshot2](https://user-images.githubusercontent.com/87825806/126681429-21cab326-b520-4f71-b728-ce3af3321220.jpg)

**Comment by rdwarren13** [comment]
Has there been a fix to this? I've been having the same issue.

**Comment by ceyhuntansu** [comment]
uninstalled flax, deleted flax directory and reinstalled...needed to sync allover again but working fine right now...

**Comment by rdwarren13** [comment]
Thank you. I had to uninstall Flax, delete the Wallet DB, and then
reinstall.
