### ISSUE TITLE
[BUG] NOT FOUND PROFITS UNESTABLE CONNECTION (CLOSED COMUNICATION WITH REMOTE NODES)

### ISSUE THREAD

**Issue by cokiPL** [Flax-Network/flax-blockchain#34]
Scenario:

Full node are working standalone with CHIA + FLAX

CHIA work good, I add manually port forward in my router 8444, config  upnp : enable
FLAX add manually port Forward  6444, config  upnp : enable

In my router: UPNP enable

I testing with firewall:
firewall in machine off
firewall in router off

config from FLAX

  pool_share_threshold: 1000
  port: 6885
  rpc_port: 6759
  selected_network: mainnet
  ssl:
    private_crt: config/ssl/farmer/private_farmer.crt
    private_key: config/ssl/farmer/private_farmer.key
    public_crt: config/ssl/farmer/public_farmer.crt
    public_key: config/ssl/farmer/public_farmer.key
  start_rpc_server: true
  xfx_target_address: xfx1vqzylmzjk9saw7ttunuq5gh9ppu2fe2shxrsp2tyjpwsusmkylssqnvwkd
flax_ssl_ca:
  crt: config/ssl/ca/flax_ca.crt
  key: config/ssl/ca/flax_ca.key
full_node:
  database_path: db/blockchain_v1_CHALLENGE.sqlite
  dns_servers:
  - dns-introducer.flaxnetwork.org
  enable_profiler: false
  enable_upnp: true
  exempt_peer_networks: []
  farmer_peer:
    host: localhost
    port: 6885
  introducer_peer:
    host: introducer.flaxnetwork.org
    port: 6888
  logging: *id001
  max_inbound_farmer: 10
  max_inbound_timelord: 5
  max_inbound_wallet: 15
  network_overrides: *id002
  peer_connect_interval: 30
  peer_db_path: db/peer_table_node.sqlite
  port: 6888
  recent_peer_threshold: 6000
  rpc_port: 6755
  sanitize_weight_proof_only: false
  selected_network: mainnet
  send_uncompact_interval: 0
  short_sync_blocks_behind_threshold: 20
  simulator_database_path: sim_db/simulator_blockchain_v1_CHALLENGE.sqlite
  simulator_peer_db_path: sim_db/peer_table_node.sqlite
  ssl:
    private_crt: config/ssl/full_node/private_full_node.crt
    private_key: config/ssl/full_node/private_full_node.key
    public_crt: config/ssl/full_node/public_full_node.crt
    public_key: config/ssl/full_node/public_full_node.key
  start_rpc_server: true
  sync_blocks_behind_threshold: 300
  target_outbound_peer_count: 20
  target_peer_count: 15
  target_uncompact_proofs: 300
  timelord_peer:
    host: localhost
    port: 6886
  wallet_peer:
    host: localhost
    port: 6883
  weight_proof_timeout: 360
harvester:
  farmer_peer:
    host: localhost
    port: 6885
  flax_ssl_ca:
    crt: config/ssl/ca/flax_ca.crt
    key: config/ssl/ca/flax_ca.key
  logging: *id001
  network_overrides: *id002
  num_threads: 30
  plot_directories:
  - G:\plot
  - H:\plot
  - I:\plot
  - J:\plot
  - L:\plot
  - N:\plot
  - O:\plot
  - Q:\plot
  - R:\plot
  - S:\plot
  - T:\plot
  - V:\miner
  - E:\plot
  - D:\plot
  - F:\plot
  - K:\plot
  - M:\plot
  - I:\plot
  - U:\plot 18
  - P:\plot
  plot_loading_frequency_seconds: 120
  port: 6884
  private_ssl_ca:
    crt: config/ssl/ca/private_ca.crt
    key: config/ssl/ca/private_ca.key
  rpc_port: 6760
  selected_network: mainnet
  ssl:
    private_crt: config/ssl/harvester/private_harvester.crt
    private_key: config/ssl/harvester/private_harvester.key
  start_rpc_server: true
inbound_rate_limit_percent: 100
introducer:
  host: localhost
  logging: *id001
  max_peers_to_send: 15
  network_overrides: *id002
  port: 6887
  recent_peer_threshold: 6000
  selected_network: mainnet
  ssl:
    public_crt: config/ssl/full_node/public_full_node.crt
    public_key: config/ssl/full_node/public_full_node.key
logging: *id001
min_mainnet_k_size: 32
network_overrides: *id002
outbound_rate_limit_percent: 30
ping_interval: 120
pool:
  logging: *id001
  network_overrides: *id002
  selected_network: mainnet
  xfx_target_address: xfx1vqzylmzjk9saw7ttunuq5gh9ppu2fe2shxrsp2tyjpwsusmkylssqnvwkd
private_ssl_ca:
  crt: config/ssl/ca/private_ca.crt
  key: config/ssl/ca/private_ca.key
selected_network: mainnet
self_hostname: localhost
timelord:
  fast_algorithm: false
  full_node_peer:
    host: localhost
    port: 6888
  logging: *id001
  max_connection_time: 60
  network_overrides: *id002
  port: 6886
  sanitizer_mode: false
  selected_network: mainnet
  ssl:
    private_crt: config/ssl/timelord/private_timelord.crt
    private_key: config/ssl/timelord/private_timelord.key
    public_crt: config/ssl/timelord/public_timelord.crt
    public_key: config/ssl/timelord/public_timelord.key
  vdf_clients:
    ip:
    - localhost
    - localhost
    - 127.0.0.1
    ips_estimate:
    - 150000
  vdf_server:
    host: localhost
    port: 6600
timelord_launcher:
  logging: *id001
  port: 6600
  process_count: 3
ui:
  daemon_host: localhost
  daemon_port: 56600
  daemon_ssl:
    private_crt: config/ssl/daemon/private_daemon.crt
    private_key: config/ssl/daemon/private_daemon.key
  logging: *id001
  network_overrides: *id002
  port: 6222
  rpc_port: 6755
  selected_network: mainnet
  ssh_filename: config/ssh_host_key
wallet:
  database_path: wallet/db/blockchain_wallet_v1_CHALLENGE_KEY.sqlite
  full_node_peer:
    host: localhost
    port: 6888
  initial_num_public_keys: 100
  initial_num_public_keys_new_wallet: 5
  introducer_peer:
    host: introducer.flaxnetwork.org
    port: 6888
  logging: *id001
  network_overrides: *id002
  num_sync_batches: 50
  peer_connect_interval: 60
  port: 6883
  recent_peer_threshold: 6000
  rpc_port: 6761
  selected_network: mainnet
  ssl:
    private_crt: config/ssl/wallet/private_wallet.crt
    private_key: config/ssl/wallet/private_wallet.key
    public_crt: config/ssl/wallet/public_wallet.crt
    public_key: config/ssl/wallet/public_wallet.key
  start_height_buffer: 100
  starting_height: 0
  target_peer_count: 8
  testing: false
  trusted_peers:
    trusted_node_1: config/ssl/full_node/public_full_node.crt
  wallet_peers_path: wallet/db/wallet_peers.sqlite

Logs from FLAX

> 

```
> 2021-08-07T10:24:02.931 full_node full_node_server        : INFO     Not accepting inbound connection: {'host': '218.68.227.236', 'port': 6888}.Inbound limit reached.
> 2021-08-07T10:24:03.108 full_node full_node_server        : INFO     Connection closed: 218.68.227.236, node id: e19578dcab9c2a4766400e1071ea3e9346831d340ba2bde0784d12aa5f132ea7
> 2021-08-07T10:24:03.109 full_node flax.full_node.full_node: INFO     peer disconnected {'host': '218.68.227.236', 'port': 6888}
> 2021-08-07T10:24:04.523 full_node full_node_server        : INFO     Not accepting inbound connection: {'host': '115.196.195.145', 'port': 6888}.Inbound limit reached.
> 2021-08-07T10:24:04.843 full_node full_node_server        : INFO     Not accepting inbound connection: {'host': '223.88.102.125', 'port': 6888}.Inbound limit reached.
> 2021-08-07T10:24:04.851 full_node full_node_server        : INFO     Connection closed: 115.196.195.145, node id: 498d8767deeb16aecf413b19cdbcffd7995631ba233a87f833175a475de2336a
> 2021-08-07T10:24:04.852 full_node flax.full_node.full_node: INFO     peer disconnected {'host': '115.196.195.145', 'port': 6888}
> 2021-08-07T10:24:05.020 full_node flax.full_node.full_node: INFO     Already compactified block: 99274a2be7b0a7f7767ea5f17d6febe08f73e4738767bf84549c2b6a9c96999f. Ignoring.
> 2021-08-07T10:24:05.032 full_node flax.full_node.full_node: INFO     Already compactified block: 99274a2be7b0a7f7767ea5f17d6febe08f73e4738767bf84549c2b6a9c96999f. Ignoring.
> 2021-08-07T10:24:05.043 full_node flax.full_node.full_node: INFO     Already compactified block: 99274a2be7b0a7f7767ea5f17d6febe08f73e4738767bf84549c2b6a9c96999f. Ignoring.
> 2021-08-07T10:24:05.142 full_node full_node_server        : INFO     Connection closed: 223.88.102.125, node id: 49a002832c5c2a682d9df9da815ba9e3afce5d159362ec9ae2f81e9e34171cae
> 2021-08-07T10:24:05.143 full_node flax.full_node.full_node: INFO     peer disconnected {'host': '223.88.102.125', 'port': 6888}
> 2021-08-07T10:24:05.969 full_node flax.full_node.full_node: INFO       Finished signage point 27/64: CC: 406d86a5f6c501912f4a99b90ee56cf322c1adfa5ef3dddd70089875787c17ca RC: d52b07bfd531d2ad4808465081b1e616cb2bc3d21fb22ce9f60adf269e67963d 
> 2021-08-07T10:24:06.143 harvester flax.harvester.harvester: INFO     4 plots were eligible for farming 0bd8b7fdeb... Found 0 proofs. Time: 0.17116 s. Total 1505 plots
> 2021-08-07T10:24:06.285 full_node full_node_server        : INFO     Not accepting inbound connection: {'host': '219.134.116.207', 'port': 6888}.Inbound limit reached.
> 2021-08-07T10:24:06.583 full_node full_node_server        : INFO     Not accepting inbound connection: {'host': '39.182.56.200', 'port': 6888}.Inbound limit reached.
> 2021-08-07T10:24:06.597 full_node full_node_server        : INFO     Connection closed: 219.134.116.207, node id: c8e149ed68256d424caff6e1757a6b2a67c0ab63f3cdb77c818ce8900d9ef50a
> 2021-08-07T10:24:06.598 full_node flax.full_node.full_node: INFO     peer disconnected {'host': '219.134.116.207', 'port': 6888}
> 2021-08-07T10:24:06.878 full_node full_node_server        : INFO     Connection closed: 39.182.56.200, node id: 15ffac28d643e01e1758ac8cd81276f5ee1337038890bdec3636d4c092003240
> 2021-08-07T10:24:06.879 full_node flax.full_node.full_node: INFO     peer disconnected {'host': '39.182.56.200', 'port': 6888}
> 2021-08-07T10:24:07.008 full_node full_node_server        : INFO     Not accepting inbound connection: {'host': '42.234.8.19', 'port': 6888}.Inbound limit reached.
> 2021-08-07T10:24:07.190 full_node full_node_server        : INFO     Connection closed: 42.234.8.19, node id: abcf6ef95ddb3c85406a84c6dc83b2e815fe774c2291425e4612de42edbdca2d
> 2021-08-07T10:24:07.191 full_node flax.full_node.full_node: INFO     peer disconnected {'host': '42.234.8.19', 'port': 6888}
> 2021-08-07T10:24:07.718 full_node full_node_server        : INFO     Not accepting inbound connection: {'host': '180.116.38.93', 'port': 6888}.Inbound limit reached.
> 2021-08-07T10:24:08.072 full_node full_node_server        : INFO     Connection closed: 180.116.38.93, node id: 70228e8e0a6be885e8f564a0539595ef64762c6b4f9c97f3dd3ad5b8f0ecc0cc
> 2021-08-07T10:24:08.073 full_node flax.full_node.full_node: INFO     peer disconnected {'host': '180.116.38.93', 'port': 6888}
> 2021-08-07T10:24:12.741 full_node full_node_server        : INFO     Not accepting inbound connection: {'host': '14.114.196.220', 'port': 6888}.Inbound limit reached.
> 2021-08-07T10:24:13.066 full_node full_node_server        : INFO     Connection closed: 14.114.196.220, node id: 1c9c460a26fa330dcaeb1b98091b1c56092e76b030e40f333b8ac95c0be9375b
> 2021-08-07T10:24:13.067 full_node flax.full_node.full_node: INFO     peer disconnected {'host': '14.114.196.220', 'port': 6888}
> 2021-08-07T10:24:13.769 full_node flax.full_node.full_node: INFO      Updated peak to height 277285, weight 21734614007, hh dfa8396d704e802b8b92c5a48a6e15a08b5256eeac4afa5726eef35783c9b832, forked at 277284, rh: 12bf50352c0b474ed53688d20c5e5a3afbe2ac4a8bbe4a0f25b9b21220b187f3, total iters: 618636481835, overflow: False, deficit: 3, difficulty: 119296, sub slot iters: 79691776, Generator size: No tx, Generator ref list size: No tx
> 2021-08-07T10:24:13.774 full_node flax.full_node.full_node: INFO     Block validation time: 0.27625131607055664, cost: None
> 2021-08-07T10:24:13.982 wallet flax.wallet.wallet_blockchain: INFO      Updated wallet peak to height 277285, weight 21734614007, 
> 2021-08-07T10:24:15.768 full_node full_node_server        : INFO     Not accepting inbound connection: {'host': '94.74.139.27', 'port': 6888}.Inbound limit reached.
> 2021-08-07T10:24:15.928 full_node flax.full_node.full_node: INFO       Finished signage point 28/64: CC: 68b63926845b5cd0f3954fde4d4944222724ce302ab9feee1c14c661f5907186 RC: dc2f1b58c787c3cce72eaa57ecc3b9b10a8e5b49304d81ff8ca675192b3bd379 
> 2021-08-07T10:24:15.931 full_node full_node_server        : INFO     Connection closed: 94.74.139.27, node id: d6c8fb390286d1f4090077e0f003e3185fd358c1e099b058addad09b2f9fb008
> 2021-08-07T10:24:15.932 full_node flax.full_node.full_node: INFO     peer disconnected {'host': '94.74.139.27', 'port': 6888}
> 2021-08-07T10:24:16.168 harvester flax.harvester.harvester: INFO     2 plots were eligible for farming 0bd8b7fdeb... Found 0 proofs. Time: 0.23621 s. Total 1505 plots
> 2021-08-07T10:24:18.214 full_node full_node_server        : INFO     Not accepting inbound connection: {'host': '180.110.101.15', 'port': 6888}.Inbound limit reached.
> 2021-08-07T10:24:18.534 full_node full_node_server        : INFO     Connection closed: 180.110.101.15, node id: e0e1fee0c931c13db655eef34e4ae75578551e0ad8a22f3ed9378f56a7645b5a
> 2021-08-07T10:24:18.535 full_node flax.full_node.full_node: INFO     peer disconnected {'host': '180.110.101.15', 'port': 6888}
> 2021-08-07T10:24:21.273 full_node full_node_server        : INFO     Cannot connect to host 36.227.143.92:6888 ssl:<ssl.SSLContext object at 0x00000253ACE18208> [Connect call failed ('36.227.143.92', 6888)]
> 2021-08-07T10:24:23.395 full_node flax.full_node.full_node: INFO       Finished signage point 29/64: CC: c03c18639c86039be6cfcf31807dcffd93e9467f1ccb151a197922596498d9e0 RC: 8a1c4c6212a3acf8f804541e90874076c4842b131f08a51f05f7d0e6832c4a6a 
> 2021-08-07T10:24:23.398 full_node full_node_server        : INFO     Not accepting inbound connection: {'host': '219.136.77.212', 'port': 6888}.Inbound limit reached.
> 2021-08-07T10:24:23.595 harvester flax.harvester.harvester: INFO     1 plots were eligible for farming 0bd8b7fdeb... Found 0 proofs. Time: 0.19718 s. Total 1505 plots
> 2021-08-07T10:24:23.722 full_node full_node_server        : INFO     Connection closed: 219.136.77.212, node id: 35fbd4f586bab405f72d0722592f71eac2a3e4c6193309901bd673aa47b22f5b
> 2021-08-07T10:24:23.723 full_node flax.full_node.full_node: INFO     peer disconnected {'host': '219.136.77.212', 'port': 6888}
```

> 

I add manually flax nodes 

Im frustated... 30 days, 2000 plots 0 FLAX

**Comment by Oscillator098** [comment]
Check the FlaxExplorer.org
and your wallet from config that you provided : xfx1vqzylmzjk9saw7ttunuq5gh9ppu2fe2shxrsp2tyjpwsusmkylssqnvwkd
It is winning blocks.
Maybe it is cold wallet and It doesn't show on GUI. GUI only shows "Hot" wallet and if Cold wallet won the block on GUI it will show nothing.

**Comment by cokiPL** [comment]
hI!

thanks for reply...

My original adress is xfx16ah66lkh95vystnvtm67hzema6vp73q00vfhphqq6rnetxk4zflspt535r


This adress is not mine :(

I dont renew adress in GUI... What is happening...?

**Comment by cokiPL** [comment]
I dont know If I renew adress or what!! Can I revert for adress xfx1vqzylmzjk9saw7ttunuq5gh9ppu2fe2shxrsp2tyjpwsusmkylssqnvwkd


In my GUI appear xfx16ah66lkh95vystnvtm67hzema6vp73q00vfhphqq6rnetxk4zflspt535r, I changed manually in config and not  work...

**Comment by cokiPL** [comment]
Im renew in config,

but when GUI is sync not appear correct walledta adress and logs appear:

021-08-07T12:37:44.398 full_node full_node_server        : INFO     Connected with full_node {'host': '86.22.239.54', 'port': 6888}
2021-08-07T12:37:44.399 wallet flax.wallet.wallet_state_manager: INFO     Confirmed balance amount is 0
2021-08-07T12:37:44.399 wallet flax.wallet.wallet_state_manager: INFO     Confirmed balance amount is 0

**Comment by Oscillator098** [comment]
The ***535r can't be found in FlaxExplorer.
Still... your farm found a block but and reward got somewhere so it is working fine.
It is hard to say what happened to your reward target if you don't own it.

**Comment by cokiPL** [comment]
True... I dont know what happenning...

I have another computer working as farmer (in local network) 

GUI from flax download from original official page... malicius software... nop (I just scan with antimalware and nothing detected)


How can fix it?

**Comment by Oscillator098** [comment]
I don't know, maybe somebody from Flax team can help?

**Comment by cokiPL** [comment]
Appreciate!

**Comment by cokiPL** [comment]
some body from Flax team can help me?

**Comment by cokiPL** [comment]
I comunicate I solved problem, was not BUG from FLAX, this issue was a big bistake for me, In past I configured WALLET as new, not import seed from original CHIA node.

Now I import seed from last FLAX (1 st instalation), next import second seed (fail with not proofs, original CHIA node), now in GUI I have two wallets, both are farming, I thnk not produce mestakes, I confirm receive 8 flax :)
