### ISSUE TITLE
does not recognize chia plots

### ISSUE THREAD

**Issue by Marv-toothy** [Flax-Network/flax-blockchain#4]
installed and synced and added directories, but no plots?

**Comment by ikniaz** [comment]
hello there!my node also stuck.i delete and try new sync but nothing.devs!please share blockchain_v1_mainnet.sqlite for fast sync. thanks!

**Comment by VisualWebTech** [comment]
lots of people have same issue try to close the original chia and flax than start first flax and then chia (if using both) this worked for many people

**Comment by room101-dev** [comment]
> installed and synced and added directories, but no plots?

Seems to be a 'windows' problem; Just quit using windows, problem will be solved. Also its silly to be running chia-net, as its impossible to solo-mine at 25EB, 

The only combo that makes sense here is HPOOL & Flax, that is no problem, my XFX are coming in daily :)

**Comment by flax-dev** [comment]
Please see FAQ on Discord. You must use the same key and open it before hpool.
