### ISSUE TITLE
[BUG] 25 words instead of 24 when creating a new wallet

### ISSUE THREAD

**Issue by harambasapp** [Flax-Network/flax-blockchain#42]
You have the same issue as I have already reported on Chia-Network/chia-blockchain.

https://github.com/Chia-Network/chia-blockchain/issues/8439
(https://images.gitee.com/uploads/images/2021/0912/003919_2dc00ad5_9717255.png "nchain error.PNG")

**Comment by flax-dev** [comment]
Thanks, fixed in version 0.1.2.
